branch-defaults:
  master:
    environment: node-express-dev
    group_suffix: null
global:
  application_name: node-express
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  profile: eb-cli
  sc: git
